# Generated by Django 3.1.4 on 2021-03-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('song_name', models.CharField(max_length=512)),
                ('song_url', models.URLField(max_length=1024)),
                ('vocal_url', models.URLField(blank=True, max_length=1024)),
                ('vocal', models.FileField(blank=True, upload_to='vocals/')),
            ],
        ),
    ]
