# Generated by Django 3.1.4 on 2021-03-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vocals',
            new_name='Vocal',
        ),
    ]
